In [1]:
import numpy as np


In [2]:
x=np.array([1,4,7,9,8,6])
x

array([1, 4, 7, 9, 8, 6])

In [3]:
x[4]

8

In [4]:
x>5

array([False, False,  True,  True,  True,  True])

In [5]:
x[x>5]

array([7, 9, 8, 6])

In [6]:
x[[3,4]]

array([9, 8])

In [7]:
x=np.random.randn(10,10)

In [8]:
x

array([[-0.64856241,  0.81887485, -2.23008685, -1.27944586,  0.12393766,
         0.88252796, -1.23249555, -1.60403658, -0.36648718,  1.10020794],
       [-1.49419678,  1.95418072,  0.4086847 ,  0.95839652,  2.10643625,
        -0.02185256, -0.86169104, -0.46062374,  0.82811743, -1.61860584],
       [ 0.39880944, -0.76191717, -0.36260076,  1.84045585, -1.53430671,
        -0.51327222,  1.08001688, -1.20902583, -0.19355962, -0.57614011],
       [-0.54314176, -0.65830698, -0.14077805, -0.56503702,  1.32028904,
         0.66917713, -0.85445188, -0.16188862, -1.80282556,  0.89037243],
       [ 2.5260006 ,  0.58730631,  0.42708657, -0.75008508, -0.63695979,
        -0.54750164,  0.64300419, -0.0696639 , -0.19010923,  2.08104481],
       [ 1.21066049,  0.61176268,  1.07818345,  0.42229889,  1.65921142,
         1.53696665, -0.24799506,  0.30773048, -2.46935238, -0.71513656],
       [ 1.79368329,  1.12485246,  1.31563865,  0.6935904 ,  0.88733614,
        -0.46706743, -0.57527227, -1.9264781 

In [9]:
x[0]

array([-0.64856241,  0.81887485, -2.23008685, -1.27944586,  0.12393766,
        0.88252796, -1.23249555, -1.60403658, -0.36648718,  1.10020794])

In [10]:
x[0,4]

0.12393766298263777

In [15]:
x[3:10:2]

array([[-0.54314176, -0.65830698, -0.14077805, -0.56503702,  1.32028904,
         0.66917713, -0.85445188, -0.16188862, -1.80282556,  0.89037243],
       [ 1.21066049,  0.61176268,  1.07818345,  0.42229889,  1.65921142,
         1.53696665, -0.24799506,  0.30773048, -2.46935238, -0.71513656],
       [ 0.19502816, -0.64862852, -0.23241431, -0.37231318,  0.34850253,
         0.20932072, -1.23134133, -0.36443698, -0.900004  ,  0.74688798],
       [ 0.08538621, -0.05745856,  0.1847193 , -0.02320195, -0.86599281,
        -1.02807385,  1.96684186,  1.31861091, -0.19738442, -0.82799356]])

In [25]:
y=np.ones([10,10])
y
y[1:-1,1:-1]=0

In [26]:
y

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])