In [1]:
import numpy as np
x=np.array([10,8,9,5,1,11,8,1,9,6,2])
x

array([10,  8,  9,  5,  1, 11,  8,  1,  9,  6,  2])

In [3]:
x.mean()

6.363636363636363

In [6]:
x.cumsum()

array([10, 18, 27, 32, 33, 44, 52, 53, 62, 68, 70], dtype=int32)

In [7]:
x.cumprod()

array([      10,       80,      720,     3600,     3600,    39600,
         316800,   316800,  2851200, 17107200, 34214400], dtype=int32)

In [10]:
y= x>6
y

array([ True,  True,  True, False, False,  True,  True, False,  True,
       False, False])

In [11]:
y.sum()

6

In [12]:
y.any()

True

In [13]:
y.all()

False

In [14]:
x.sort()

In [16]:
np.unique(x)

array([ 1,  2,  5,  6,  8,  9, 10, 11])

In [17]:
y.sort()

In [18]:
np.unique(y)

array([False,  True])